### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by simonrenoult** [banyan/gzip-brunch#1]
I may be mistaken though. I've tried the plugin with this conf :

```
exports.config = 
  plugins:
    gzip:
      paths:
        javascript: 'js'
        stylesheet: 'css'
```

My js and css files are stored in `public/js` and `public/css` so that seems fine. However nothing happens when i build my project using `brunch build`. 

I may have spotted one issue. Your application requires zlib but does not automatically install it. I'v manually istalled it but it still does not wok.
